(() => {
  'use strict';
  const catalog=window.SPS_F_SERVICES, shared=window.SPS_CONTENT;
  const requested=new URLSearchParams(location.search).get('service');
  const key=Object.hasOwn(catalog,requested)?requested:'management';
  const s=catalog[key], hub=document.body.dataset.fPage==='services';
  const serviceCards=(exclude)=>Object.entries(catalog).filter(([id])=>id!==exclude).map(([id,item],i)=>`<a class="f-service-choice" href="f-service.html?service=${id}" id="service-${id}"><div class="f-choice-image"><img src="${item.image}" alt="소개용 공간 이미지 · 실제 관리 건물 아님" loading="lazy"></div><div><span class="f-eyebrow">${item.english}</span><h2>${item.title}<span aria-hidden="true">↗</span></h2><p>${item.short}</p><span class="f-choice-action">이 서비스 살펴보기 →</span></div></a>`).join('');
  if(hub){
    document.querySelector('#f-detail').innerHTML=`<section class="f-hub-intro wrap"><p class="f-breadcrumb"><a href="f-home.html">SPS 홈</a> / 서비스</p><p class="f-eyebrow">Choose your service</p><h1>지금 가장 막히는 일부터,<br>맡길 범위를 찾아보세요.</h1><p>같은 건물이어도 필요한 관리는 다릅니다.<br>고민에 가까운 서비스를 선택해, 제공 방식과 조건을 살펴보세요.</p></section><section class="f-service-choices wrap" aria-label="서비스 선택">${serviceCards()}</section><section class="f-hub-note wrap"><p>서비스 범위에 따라 요금이 달라집니다. 개별 포함 업무와 비용은 상담 후 합의합니다.</p><p>소개용 이미지는 실제 관리 건물이나 실적을 나타내지 않습니다.</p><button class="f-button" data-f-consult>상담 절차 알아보기 <span>↗</span></button></section>`;return;
  }
  document.title=`${s.title} — SPS`;
  const r=shared.records.find(item=>item.id===s.record);
  const report=r?`<div class="f-report" id="report-sample"><div class="f-report-meta"><strong>관리 보고 예시</strong><span>${shared.sampleLabel}</span></div><p class="f-small">${shared.building} · ${shared.asOf}</p><div class="f-report-summary"><div><p class="f-eyebrow">${r.id} / ${r.location}</p><h3>${r.status}</h3><p>${r.caution}</p></div><span class="f-state-label">확인 중</span></div><dl class="f-report-fields"><div><dt>현재 상태</dt><dd>${r.finding}</dd></div><div><dt>남은 확인</dt><dd>${r.next}</dd></div><div><dt>담당·기한</dt><dd>${r.owner} · 처리 기한 미정</dd></div></dl><button class="f-text-link" data-f-evidence="${r.id}" id="f-evidence-open">근거와 부족한 자료 보기 <span aria-hidden="true">↗</span></button><p class="f-small f-report-plan">${shared.reportPlan}</p></div>`:`<div class="f-report f-empty-report" id="report-sample"><div class="f-report-meta"><strong>공실 보고 구성 예시</strong><span>실제 건물·공실 정보가 아닙니다.</span></div><p class="f-eyebrow">자료 확인 전</p><h3>진행 상황을 정리할<br>자료가 아직 없습니다.</h3><p>자료가 없다는 이유로 공실이 없거나 임대가 완료됐다고 표시하지 않습니다.</p><dl class="f-report-fields"><div><dt>공실 현황</dt><dd>호실·현재 상태 자료 필요</dd></div><div><dt>임대 조건</dt><dd>희망 조건·협의 내용 확인 필요</dd></div><div><dt>담당 범위</dt><dd>관리·중개 담당과 조건 합의 필요</dd></div></dl><button class="f-text-link" data-f-prepare id="f-evidence-open">먼저 확인할 자료 보기 <span aria-hidden="true">↗</span></button><p class="f-small f-report-plan">${shared.reportPlan}</p></div>`;
  document.querySelector('#f-detail').innerHTML=`
    <section class="f-service-hero"><div class="wrap f-service-hero-grid"><div><p class="f-breadcrumb"><a href="f-home.html">SPS 홈</a><span>/</span><a href="f-services.html">서비스</a><span>/</span>${s.title}</p><p class="f-eyebrow">${s.english}<span class="f-plan">제공 방식 · 계획</span></p><h1>${s.headline}</h1><p class="f-hero-lead">${s.lead}</p><a class="f-button f-button-light" href="#situation">관리 방식 살펴보기 <span>↓</span></a><a class="f-hero-secondary" href="#scope">상담 전 범위·비용 확인 ↗</a></div><figure><img src="${s.image}" alt="${s.title} 소개용 공간 이미지" fetchpriority="high"><figcaption>소개용 이미지 · 실제 관리 건물 아님</figcaption><span class="f-image-line" aria-hidden="true"></span></figure></div></section>
    <nav class="f-section-nav" aria-label="서비스 상세 목차"><div class="wrap"><a href="#situation">이런 상황이라면</a><a href="#approach">맡길 일</a><a href="#report">보고 예시</a><a href="#scope">범위·비용</a><a href="#consult">상담 안내</a></div></nav>
    <section class="f-section wrap f-situation" id="situation"><div class="f-section-heading" data-f-reveal><p class="f-eyebrow">Your situation</p><h2>${s.problemTitle}</h2></div><div class="f-situation-list">${s.situations.map(([title,text],i)=>`<article data-f-reveal><span class="f-number">0${i+1}</span><div><h3>${title}</h3><p>${text}</p></div></article>`).join('')}</div><p class="f-bridge" data-f-reveal>${s.bridge}</p></section>
    <section class="f-approach" id="approach"><div class="wrap f-section"><div class="f-section-heading" data-f-reveal><p class="f-eyebrow">The way we work · 제공 계획</p><h2>${s.approachTitle}</h2></div><div class="f-steps">${s.steps.map(([title,text],i)=>`<article data-f-reveal><span class="f-number">0${i+1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div><div class="f-agreement"><span>건물주와 함께 정할 일</span><p>${s.owner}</p></div></div></section>
    <section class="f-section wrap" id="report"><div class="f-section-heading f-report-intro" data-f-reveal><div><p class="f-eyebrow">One clear briefing</p><h2>${s.reportTitle}</h2></div><p>운영을 맡긴 뒤에도,<br>상태 → 근거 → 다음 확인이 이어지도록.<br><span>아래는 제공 방식을 설명하는 예시입니다.</span></p></div>${report}</section>
    <section class="f-origin"><div class="wrap"><p class="f-eyebrow">Why SPS</p><h2>맡긴 뒤의 막막함을,<br>우리도 겪었습니다.</h2><div><p>소장에게 관리를 맡겼지만 미납 규모를 알기 어려웠고, 시설 관리가 충분히 이루어지지 않는 문제를 겪었습니다.</p><p>그 경험에서, 업무를 맡기는 것과 현재 상황을 아는 일이 함께 가야 한다고 생각했습니다.</p><p class="f-small">설립자의 문제 경험입니다. 개선 성과나 회수 실적을 입증하는 사례는 아닙니다.</p></div></div></section>
    <section class="f-section wrap" id="scope"><div class="f-section-heading" data-f-reveal><p class="f-eyebrow">Scope & conditions</p><h2>맡길 범위가 달라지면,<br>요금도 달라집니다.</h2><p>포함 업무와 별도 업무를 구분한 뒤 관리 범위를 합의합니다.</p></div><dl class="f-scope-list">${s.scope.map(([t,d])=>`<div><dt>${t}</dt><dd>${d}</dd></div>`).join('')}</dl><div class="f-price-note"><h3>금액은 범위별 견적 후 합의합니다.</h3><p>${shared.price} ${shared.exclusions}</p><p>현장 진단 비용, 서비스 지역·수용 가능한 건물 규모는 확정 전입니다.</p></div></section>
    <section class="f-process-band"><div class="wrap f-section"><p class="f-eyebrow">Getting started · 제공 계획</p><h2>상담에서 현재를 살피고,<br>맡길 범위를 정합니다.</h2><ol>${shared.steps.map(([title,desc],i)=>`<li><span class="f-number">0${i+1}</span><h3>${title}</h3><p>${desc}</p></li>`).join('')}</ol></div></section>
    <section class="f-section wrap f-faq"><div><p class="f-eyebrow">Before you decide</p><h2>맡기기 전에,<br>확인할 내용.</h2></div><div><details><summary>${s.question}<span>+</span></summary><p>${s.answer}</p></details><details><summary>월간 보고서와 앱을 지금 사용할 수 있나요?<span>+</span></summary><p>${shared.reportPlan} 이 페이지는 실제 고객용 앱이나 실시간 운영 현황이 아닙니다.</p></details><details><summary>필요한 업무만 맡길 수 있나요?<span>+</span></summary><p>시설·임차인 요청, 미납 대응, 임차·공실 관리 중 필요한 범위를 협의합니다. 개별 포함 업무와 별도 비용은 확정 계약에서 확인해야 합니다.</p></details></div></section>
    <section class="f-consult" id="consult"><div class="wrap"><p class="f-eyebrow">Your next step</p><h2>우리 건물에,<br>무엇부터 맡길까요?</h2><div class="f-consult-bottom"><p>${s.title}에서 확인할 자료와<br>상담 이후 절차를 살펴보세요.</p><div><button class="f-button f-button-light" data-f-consult id="f-consult-open">${s.title} 상담 안내 <span>↗</span></button><p class="f-small">절차 안내만 제공합니다. 실제 상담은 접수되지 않습니다.</p></div></div></div></section>
    <section class="f-related wrap"><div><p class="f-eyebrow">Other services</p><h2>다른 일도 맡겨야 한다면.</h2></div><div>${Object.entries(catalog).filter(([id])=>id!==key).map(([id,item])=>`<a href="f-service.html?service=${id}">${item.title}<span>↗</span></a>`).join('')}<a href="f-services.html">서비스 다시 선택<span>↩</span></a><a href="f-home.html#services">메인의 서비스 목록<span>↩</span></a></div></section>`;
})();
