(() => {
  'use strict';
  const catalog=window.SPS_G_SERVICES, shared=window.SPS_CONTENT;
  const requested=new URLSearchParams(location.search).get('service');
  const key=window.spsGServiceKey(requested);
  const s=catalog[key], copy=window.SPS_G_COPY[key];
  document.title=`${s.title} 상담 — SPS`;
  const arrow='<span aria-hidden="true">↗</span>';
  const cta=(text='우리 건물 상담 신청',style='g-button')=>`<a class="${style}" href="#consult">${text}${arrow}</a>`;
  const records=(s.records || [s.record]).map(id=>shared.records.find(r=>r.id===id)).filter(Boolean);
  const report=records.length?records.map(record=>`<article class="g-report-record"><div class="g-report-head"><span>관리 보고 예시</span><span>${shared.building} · ${record.location}</span></div><div class="g-report-main"><span class="g-label">${record.id} / ${record.category}</span><h3>${record.status}</h3><p>${record.caution}</p></div><dl class="g-report-lines"><div><dt>현재 확인</dt><dd>${record.finding}</dd></div><div><dt>다음 확인</dt><dd>${record.next}</dd></div><div><dt>담당·기한</dt><dd>${record.owner} · 처리 기한 미정</dd></div></dl><button class="f-text-link" data-f-evidence="${record.id}" id="g-evidence-${record.id}">근거와 부족한 자료 보기 ${arrow}</button><p class="g-note">예시 기준 ${shared.asOf}</p></article>`).join(''):`<div class="g-report-head"><span>공실 보고 구성 예시</span><span>실제 건물·공실 정보 아님</span></div><div class="g-report-main"><span class="g-label">자료 확인 전</span><h3>확인할 자료가<br>아직 없습니다.</h3><p>자료가 없는 상태를 공실 없음이나 임대 완료로 표시하지 않습니다.</p></div><dl class="g-report-lines"><div><dt>공실 현황</dt><dd>호실·현재 상태 자료 필요</dd></div><div><dt>임대 조건</dt><dd>희망 조건·협의 내용 확인 필요</dd></div><div><dt>담당 범위</dt><dd>관리·중개 역할 합의 필요</dd></div></dl><button class="f-text-link" data-f-prepare id="g-evidence-open">먼저 확인할 자료 보기 ${arrow}</button>`;
  document.querySelector('#g-detail').innerHTML=`
  <section class="g-hero"><div class="g-hero-photo" style="--hero-image:url('${s.image}')" aria-hidden="true"></div><div class="g-container g-hero-content"><p class="g-breadcrumb"><a href="g-home.html">SPS 홈</a><span>/</span><a href="g-services.html">서비스 소개</a><span>/</span>${s.title}</p><p class="g-label">SPS · ${s.title}</p><h1>${copy.headline}</h1><p class="g-lead">${copy.lead}</p><div class="g-hero-actions">${cta()}<a href="#situation" class="g-secondary">어떻게 관리하나요? <span aria-hidden="true">↓</span></a></div><p class="g-audience">${copy.audience}</p><p class="g-hero-disclosure">제공 방식 소개 · 상담 신청 화면은 미리보기이며 실제 접수되지 않습니다.</p></div><div class="g-hero-base g-container"><span>관리를 맡기는 것부터,<br><strong>맡긴 일을 아는 것까지.</strong></span><p>${Object.values(catalog).map(service=>service.title).join(' / ')}<br><span>소개용 이미지 · 실제 관리 건물 아님</span></p></div></section>
  <nav class="g-section-nav" aria-label="서비스 상세 목차"><div class="g-container"><a href="#situation">이런 상황이라면</a><a href="#check">내 상황 확인</a><a href="#approach">SPS의 방식</a><a href="#report">보고 예시</a><a href="#scope">범위·비용</a><a href="#consult">상담 신청 ${arrow}</a></div></nav>
  <section class="g-section g-container g-pain" id="situation"><p class="g-label">01 / 익숙한 장면</p><h2 data-f-reveal>${copy.painTitle}</h2><p class="g-intro">일을 맡겼지만, 확인하고 연결하는 일은 여전히 남아 있나요?</p><div class="g-voices">${copy.voices.map((v,i)=>`<p data-f-reveal><span aria-hidden="true">0${i+1}</span>${v}</p>`).join('')}</div><p class="g-note">고객 후기가 아닌, 관리 상황을 설명하기 위한 문장입니다.</p></section>
  <section class="g-burden"><div class="g-container g-section"><p class="g-label">02 / 반복되는 확인의 부담</p><h2 data-f-reveal>${copy.costTitle}</h2><div class="g-chain">${copy.chain.map(([t,d],i)=>`<article data-f-reveal><span class="g-step-number">0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div><p class="g-cause" data-f-reveal>${copy.cause}</p></div></section>
  <section class="g-section g-container g-check-section" id="check"><div><p class="g-label">03 / 내 건물의 현재</p><h2 data-f-reveal>지금 내 상황과<br>가까운 것은 무엇인가요?</h2><p class="g-intro">해당하는 고민을 골라보세요.<br>선택한 내용은 아래 상담 신청 화면에 이어집니다.</p><p class="g-note">위험도 진단이 아닌 상담 주제 정리입니다.<br>선택하지 않고 신청 화면으로 이동해도 됩니다.</p></div><div class="g-check-panel"><fieldset><legend class="g-sr-only">상담에서 이야기할 고민 선택</legend>${copy.checks.map((t,i)=>`<label class="g-check-row"><input type="checkbox" name="concern" value="${i}"><span>${t}</span><i aria-hidden="true"></i></label>`).join('')}</fieldset><p class="g-check-status" aria-live="polite">선택한 고민이 없습니다.</p>${cta('이 고민으로 상담 신청')}</div></section>
  <section class="g-origin"><div class="g-container g-section"><p class="g-label">04 / SPS가 시작된 이유</p><div class="g-origin-grid"><h2 data-f-reveal>맡긴 뒤의 막막함을,<br>우리도 겪었습니다.</h2><div><p class="g-origin-story">소장에게 관리를 맡겼지만,<br>미납 규모를 알기 어려웠고<br>시설 관리도 충분하지 않았습니다.</p><p>그래서 운영을 대신하는 일과, 건물주가 상황을 아는 일을 함께 풀고자 SPS를 시작했습니다.</p><p class="g-note">설립자의 문제 경험입니다. 관리 개선 성과를 입증하는 고객 사례는 아닙니다.</p></div></div></div></section>
  <section class="g-section g-container" id="approach"><p class="g-label">05 / 관리의 방식 · 제공 계획</p><h2 data-f-reveal>${s.approachTitle}</h2><div class="g-approach-grid">${s.steps.map(([t,d],i)=>`<article data-f-reveal><span class="g-step-number">0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div><div class="g-owner"><span>함께 정할 일</span><p>${s.owner}</p></div><div class="g-future"><p class="g-label">바뀌어야 할 관리 경험</p>${copy.future.map(([a,b])=>`<div><p>${a}</p><span aria-hidden="true">→</span><p>${b}</p></div>`).join('')}<p class="g-note">관리 방식이 지향하는 변화이며, 확인된 고객 성과가 아닙니다.</p></div></section>
  <section class="g-report-section" id="report"><div class="g-container g-section"><div class="g-report-heading"><div><p class="g-label">06 / 한 장의 브리핑</p><h2 data-f-reveal>${s.reportTitle}</h2></div><p>현재 상태를 읽고,<br>근거를 확인하고,<br>다음 할 일을 이해하도록.</p></div><div class="g-report-sheet">${report}</div><p class="g-note">${shared.sampleLabel}. ${shared.reportPlan}</p></div></section>
  <section class="g-section g-container" id="scope"><p class="g-label">07 / 범위와 비용</p><h2 data-f-reveal>필요한 일부터 맡기고,<br>범위에 맞춰 요금을 정합니다.</h2><p class="g-intro">${s.title}에서 맡길 일과 별도 업무를 구분합니다.</p><dl class="g-scope">${s.scope.map(([t,d])=>`<div><dt>${t}</dt><dd>${d}</dd></div>`).join('')}</dl><div class="g-conditions"><h3>상담 전에 알아두세요.</h3><p>${shared.price} ${shared.exclusions}</p><p>현장 진단 비용, 서비스 지역과 수용 가능한 건물 규모는 확정 전입니다. 상담에서 제공 가능한 조건을 확인합니다.</p></div></section>
  <section class="g-process"><div class="g-container g-section"><p class="g-label">08 / 시작하는 순서 · 제공 계획</p><h2 data-f-reveal>상담은 우리 건물의<br>현재를 살피는 것부터.</h2><ol>${shared.steps.map(([t,d],i)=>`<li><span class="g-step-number">0${i+1}</span><h3>${t}</h3><p>${d}</p></li>`).join('')}</ol></div></section>
  <section class="g-section g-container g-faq"><div><p class="g-label">09 / 신청 전 궁금한 점</p><h2>맡기기 전에,<br>확인하세요.</h2></div><div>${[[s.question,s.answer],...(s.extraFaqs||[]),...shared.faqs.map(f=>[f.q,f.a]),['상담 신청 후 바로 계약되나요?','상담 신청 화면에서 건물 상황과 필요한 업무를 정리합니다. 실제 서비스 계약과 비용은 별도로 협의하는 단계입니다. 현재 미리보기는 실제 접수·예약·계약을 진행하지 않습니다.']].map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>
  <section class="g-consult-section" id="consult"><div class="g-container g-section"><div class="g-consult-grid"><div class="g-consult-intro"><p class="g-label">10 / 상담 신청</p><h2>${copy.consultation}</h2><p>건물의 현재 상황과 필요한 업무를 정리해,<br>상담에서 확인할 내용을 준비합니다.</p><ol class="g-mini-steps"><li><span>01</span>건물 상황과 고민 입력</li><li><span>02</span>신청 내용 확인</li></ol><p class="g-form-disclosure"><strong>신청 화면 미리보기</strong>입력 내용은 이 화면에서만 사용되며 저장·전송되지 않습니다. 실제 상담이 접수되거나 담당자가 연락하지 않습니다.</p></div><div class="g-form-panel"><form id="g-consult-form"><h3>우리 건물 상담 신청</h3><p class="g-note">필수 항목을 입력하면 신청 내용을 확인할 수 있습니다.</p><label>관심 서비스 <span>필수</span><select name="service" required>${Object.entries(catalog).map(([id,o])=>`<option value="${id}"${key===id?' selected':''}>${o.title}</option>`).join('')}</select></label><div class="g-form-row"><label>이름 <span>필수</span><input name="name" autocomplete="name" maxlength="40" required placeholder="예: 홍길동"></label><label>연락처 <span>필수</span><input name="phone" type="tel" inputmode="tel" autocomplete="tel" required maxlength="20" placeholder="예: 010-0000-0000" aria-describedby="g-phone-help"></label></div><p class="g-field-help" id="g-phone-help">연락처는 숫자와 +, 괄호, 공백, 하이픈으로 입력하세요.</p><div class="g-form-row"><label>건물 소재지 <span>필수</span><input name="area" autocomplete="off" maxlength="100" required placeholder="시·구 정도로 알려주세요"></label><label>현재 관리 방식 <span>선택</span><select name="management"><option value="미선택">선택해주세요</option><option>직접 관리</option><option>소장·직원에게 위임</option><option>관리 업체 이용</option><option>기타</option></select></label></div><div class="g-form-concerns"><span>위에서 선택한 고민</span><p id="g-concerns-summary">선택한 고민이 없습니다.</p><a href="#check">고민 선택·수정 <span aria-hidden="true">↑</span></a></div><label>상담하고 싶은 내용 <span>선택</span><textarea name="message" rows="3" maxlength="1000" placeholder="현재 가장 신경 쓰이는 일, 맡기고 싶은 일을 적어주세요."></textarea></label><p class="g-note">계약서·계좌 내역 등 상세 자료는 이 화면에 입력하지 않아도 됩니다.</p><button class="g-button" type="submit">신청 내용 확인 ${arrow}</button><p class="g-form-bottom">미리보기 · 실제 접수되지 않습니다.</p></form><section id="g-review" hidden aria-labelledby="g-review-title"><p class="g-label">신청 내용 확인</p><h3 id="g-review-title" tabindex="-1">이 내용으로 상담을<br>준비할 수 있습니다.</h3><p class="g-review-notice">실제 상담은 접수되지 않았습니다.<br>아래는 입력 내용 확인 화면입니다.</p><dl id="g-review-values"></dl><button class="g-button" type="button" id="g-edit">입력 내용 수정 <span aria-hidden="true">↩</span></button><p class="g-note">수정할 때 입력 내용과 선택한 고민이 유지됩니다. 새로고침하거나 이 페이지를 떠나면 입력 내용은 사라집니다.</p></section></div></div></div></section>
  <section class="g-related g-container"><p>다른 관리도 필요하다면.</p><div>${Object.entries(catalog).filter(([id])=>id!==key).map(([id,o])=>`<a href="g-service.html?service=${id}">${o.title}${arrow}</a>`).join('')}<a href="g-services.html">서비스 소개${arrow}</a></div></section>`;

  const checked=()=>[...document.querySelectorAll('[name="concern"]:checked')].map(el=>copy.checks[Number(el.value)]);
  const updateConcerns=()=>{if(!review.hidden){review.hidden=true;form.hidden=false;}const values=checked();document.querySelector('.g-check-status').textContent=values.length?`${values.length}개의 고민을 골랐습니다. 상담에서 이야기할 내용으로 이어집니다.`:'선택한 고민이 없습니다.';document.querySelector('#g-concerns-summary').textContent=values.length?values.join(' / '):'선택한 고민이 없습니다. 직접 내용을 적어도 됩니다.';};
  document.querySelectorAll('[name="concern"]').forEach(el=>el.addEventListener('change',updateConcerns));
  const form=document.querySelector('#g-consult-form'), review=document.querySelector('#g-review');
  const phone=form.elements.phone;
  function validatePhone(){const value=phone.value.trim(),digits=value.replace(/[^0-9]/g,'');phone.setCustomValidity(!value||(/^[+0-9()\s-]+$/.test(value)&&digits.length>=9&&digits.length<=15)?'':'연락처를 숫자 9~15자리로 입력해주세요.');}
  phone.addEventListener('input',validatePhone);
  form.addEventListener('submit',event=>{
    event.preventDefault();
    validatePhone();if(!form.reportValidity())return;
    const values=new FormData(form);
    const rows=[['관심 서비스',catalog[values.get('service')].title],['이름',values.get('name')],['연락처',values.get('phone')],['건물 소재지',values.get('area')],['현재 관리 방식',values.get('management')],['선택한 고민',checked().join(' / ')||'선택 없음'],['추가 내용',values.get('message')||'입력 없음']];
    const list=document.querySelector('#g-review-values'); list.replaceChildren();
    rows.forEach(([label,value])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=String(value);row.append(dt,dd);list.append(row);});
    form.hidden=true;review.hidden=false;review.scrollIntoView({behavior:'instant',block:'start'});document.querySelector('#g-review-title').focus({preventScroll:true});
  });
  document.querySelector('#g-edit').addEventListener('click',()=>{review.hidden=true;form.hidden=false;form.scrollIntoView({behavior:'instant',block:'start'});form.elements.name.focus({preventScroll:true});});
})();
